# Generated by Django 4.2.16 on 2024-10-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingarticle",
            name="category",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clothingarticle",
            name="tagsList",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
