# Generated by Django 4.2.16 on 2024-10-08 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_clothingarticle_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likesList",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
