# Generated by Django 4.2.16 on 2024-10-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_post_likeslist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likesList",
        ),
    ]
