# Generated by Django 4.2.16 on 2024-10-08 04:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_post_likeslist"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
