# Generated by Django 4.2.16 on 2024-10-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="clothingarticle",
            name="tagsList",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
