# Generated by Django 4.2.16 on 2024-10-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_post_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
