# Generated by Django 4.2.16 on 2024-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingarticle",
            name="tags_list",
            field=models.ManyToManyField(
                related_name="clothing_articles", to="api.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tagName",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
